"""added name to soupingredients class

Revision ID: 0aed16f9913f
Revises: 6cac4397d8d2
Create Date: 2023-08-08 10:16:48.374375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aed16f9913f'
down_revision = '6cac4397d8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soup_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soup_ingredients', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
