"""testing for frontend

Revision ID: 1f003e90ca57
Revises: 0aed16f9913f
Create Date: 2023-08-08 13:12:29.269158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f003e90ca57'
down_revision = '0aed16f9913f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    op.create_table('soups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soups'))
    )
    op.create_table('soup_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('soup_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_soup_ingredients_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['soup_id'], ['soups.id'], name=op.f('fk_soup_ingredients_soup_id_soups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soup_ingredients'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soup_ingredients')
    op.drop_table('soups')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
