"""added image column to models

Revision ID: 23eac9e1ea5a
Revises: 1f003e90ca57
Create Date: 2023-08-10 08:47:40.049663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23eac9e1ea5a'
down_revision = '1f003e90ca57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    with op.batch_alter_table('soup_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    with op.batch_alter_table('soups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soups', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('soup_ingredients', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
